/**
 * Demo data aligned with typical TallyPrime chart-of-account groups and trial-balance ledger layout.
 * Use for screenshots and showcases when live Tally is unavailable.
 */

export const SAMPLE_CHART_OF_ACCOUNTS = [
  { group_name: 'Capital Account', group_parent: '', bs_pl: 'BS', dr_cr: 'C', affects_gross_profit: 'N' },
  { group_name: 'Reserves & Surplus', group_parent: 'Capital Account', bs_pl: 'BS', dr_cr: 'C', affects_gross_profit: 'N' },
  { group_name: 'Loans (Liability)', group_parent: '', bs_pl: 'BS', dr_cr: 'C', affects_gross_profit: 'N' },
  { group_name: 'Current Liabilities', group_parent: '', bs_pl: 'BS', dr_cr: 'C', affects_gross_profit: 'N' },
  { group_name: 'Duties & Taxes', group_parent: 'Current Liabilities', bs_pl: 'BS', dr_cr: 'C', affects_gross_profit: 'N' },
  { group_name: 'Sundry Creditors', group_parent: 'Current Liabilities', bs_pl: 'BS', dr_cr: 'C', affects_gross_profit: 'N' },
  { group_name: 'Current Assets', group_parent: '', bs_pl: 'BS', dr_cr: 'D', affects_gross_profit: 'N' },
  { group_name: 'Bank Accounts', group_parent: 'Current Assets', bs_pl: 'BS', dr_cr: 'D', affects_gross_profit: 'N' },
  { group_name: 'Cash-in-Hand', group_parent: 'Current Assets', bs_pl: 'BS', dr_cr: 'D', affects_gross_profit: 'N' },
  { group_name: 'Sundry Debtors', group_parent: 'Current Assets', bs_pl: 'BS', dr_cr: 'D', affects_gross_profit: 'N' },
  { group_name: 'Stock-in-Hand', group_parent: 'Current Assets', bs_pl: 'BS', dr_cr: 'D', affects_gross_profit: 'N' },
  { group_name: 'Fixed Assets', group_parent: '', bs_pl: 'BS', dr_cr: 'D', affects_gross_profit: 'N' },
  { group_name: 'Sales Accounts', group_parent: '', bs_pl: 'PL', dr_cr: 'C', affects_gross_profit: 'Y' },
  { group_name: 'Purchase Accounts', group_parent: '', bs_pl: 'PL', dr_cr: 'D', affects_gross_profit: 'Y' },
  { group_name: 'Direct Expenses', group_parent: '', bs_pl: 'PL', dr_cr: 'D', affects_gross_profit: 'Y' },
  { group_name: 'Indirect Expenses', group_parent: '', bs_pl: 'PL', dr_cr: 'D', affects_gross_profit: 'N' },
  { group_name: 'Direct Incomes', group_parent: '', bs_pl: 'PL', dr_cr: 'C', affects_gross_profit: 'Y' },
];

/**
 * Ledger-level trial balance; group_name values match SAMPLE_CHART_OF_ACCOUNTS groups.
 * Amounts in same currency unit (e.g. INR). Closing ≈ opening + net_debit − net_credit for asset/expense nature.
 */
export const SAMPLE_TRIAL_BALANCE = [
  {
    ledger_name: 'Share Capital',
    group_name: 'Capital Account',
    opening_balance: 5000000,
    net_debit: 0,
    net_credit: 0,
    closing_balance: 5000000,
  },
  {
    ledger_name: 'Retained Earnings',
    group_name: 'Reserves & Surplus',
    opening_balance: 1200000,
    net_debit: 0,
    net_credit: 185000,
    closing_balance: 1385000,
  },
  {
    ledger_name: 'HDFC Bank — Operating A/c',
    group_name: 'Bank Accounts',
    opening_balance: 845000,
    net_debit: 1240000,
    net_credit: 980000,
    closing_balance: 1105000,
  },
  {
    ledger_name: 'ICICI Bank — Collections',
    group_name: 'Bank Accounts',
    opening_balance: 320000,
    net_debit: 890000,
    net_credit: 450000,
    closing_balance: 760000,
  },
  {
    ledger_name: 'Cash',
    group_name: 'Cash-in-Hand',
    opening_balance: 45000,
    net_debit: 128000,
    net_credit: 95000,
    closing_balance: 78000,
  },
  {
    ledger_name: 'M/s Northwind Traders',
    group_name: 'Sundry Debtors',
    opening_balance: 620000,
    net_debit: 980000,
    net_credit: 720000,
    closing_balance: 880000,
  },
  {
    ledger_name: 'M/s Pacific Retail Pvt Ltd',
    group_name: 'Sundry Debtors',
    opening_balance: 280000,
    net_debit: 0,
    net_credit: 150000,
    closing_balance: 130000,
  },
  {
    ledger_name: 'Trading Stock — Finished Goods',
    group_name: 'Stock-in-Hand',
    opening_balance: 2100000,
    net_debit: 3450000,
    net_credit: 2980000,
    closing_balance: 2670000,
  },
  {
    ledger_name: 'M/s Apex Suppliers',
    group_name: 'Sundry Creditors',
    opening_balance: 480000,
    net_debit: 2650000,
    net_credit: 2720000,
    closing_balance: 3110000,
  },
  {
    ledger_name: 'GST Payable — Output',
    group_name: 'Duties & Taxes',
    opening_balance: 95000,
    net_debit: 180000,
    net_credit: 220000,
    closing_balance: 135000,
  },
  {
    ledger_name: 'GST Input — ITC',
    group_name: 'Duties & Taxes',
    opening_balance: 62000,
    net_debit: 195000,
    net_credit: 80000,
    closing_balance: 177000,
  },
  {
    ledger_name: 'Domestic Sales — 18% GST',
    group_name: 'Sales Accounts',
    opening_balance: 0,
    net_debit: 45000,
    net_credit: 4520000,
    closing_balance: 4475000,
  },
  {
    ledger_name: 'Domestic Sales — Exempt',
    group_name: 'Sales Accounts',
    opening_balance: 0,
    net_debit: 0,
    net_credit: 680000,
    closing_balance: 680000,
  },
  {
    ledger_name: 'Purchase of Goods',
    group_name: 'Purchase Accounts',
    opening_balance: 0,
    net_debit: 3180000,
    net_credit: 120000,
    closing_balance: 3060000,
  },
  {
    ledger_name: 'Freight & Forwarding',
    group_name: 'Direct Expenses',
    opening_balance: 0,
    net_debit: 142000,
    net_credit: 8000,
    closing_balance: 134000,
  },
  {
    ledger_name: 'Office Rent',
    group_name: 'Indirect Expenses',
    opening_balance: 0,
    net_debit: 95000,
    net_credit: 0,
    closing_balance: 95000,
  },
  {
    ledger_name: 'Bank Charges',
    group_name: 'Indirect Expenses',
    opening_balance: 0,
    net_debit: 12800,
    net_credit: 0,
    closing_balance: 12800,
  },
  {
    ledger_name: 'Plant & Machinery',
    group_name: 'Fixed Assets',
    opening_balance: 4200000,
    net_debit: 0,
    net_credit: 0,
    closing_balance: 4200000,
  },
];
